trigger:
- new-release/*
- main

name: CICD_$(Date:yyyyMMdd)_$(Rev:r)

variables:
  URL: https://cdn.elastic.snaplogic.com
  ORG_DEV: IDG-Dev
  ORG_TEST: IDG-Test
  ORG_PRD: IDG-Prod
  PROJECT_SPACE_TEST: 'QP7_DI_CICD'
  PROJECT_SPACE_STAGING: 'QP7 DI'
  PROJECT_STAGING: 'име на пректа (трябва да се вземе от другите среди)'

jobs:

- job: Test
  condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/')
  displayName: Build Test Project and Run Tests
  pool:
    vmImage: ubuntu-latest  
    environment: 'Test'
  steps:
  - script: |
      export RESULT=$(curl -v -X POST ${{ variables.URL }}/api/1/rest/public/assetapi/project/${{ variables.ORG_TEST }}/${{ variables.PROJECT_SPACE_TEST }} \
      -u $USER:$PASS -H \
      "Content-Type: application/json" \
      -d '{"permissions":[{"perms": ["R","W","X"],"subject_type": "USER","inherit": true,"subject": "'$USER'"}]}' \
      --trace-ascii /dev/stdout)
      echo "##vso[task.setvariable variable=RESULT]$RESULT"
    displayName: Create Test Project Space
    env:
      USER: $(user)
      PASS: $(pass)
  - script: |
      export RESULT=$(curl -X POST ${{ variables.URL }}/api/1/rest/public/assetapi/project/${{ variables.ORG }}/${{ variables.PROJECT_SPACE_TEST }}/$(Build.BuildNumber)	 \
      -u $USER:$PASS \
      -H "Content-Type: application/json" \
      -d '{"permissions":[{"perms": ["R","W","X"],"subject_type": "USER","inherit": true,"subject": "'$USER'"}]}' \
      --trace-ascii /dev/stdout)
      echo "##vso[task.setvariable variable=RESULT]$RESULT"
    displayName: Create Test Project
    env:
      USER: $(user)
      PASS: $(pass)
  - script: |
      # curl -X POST ${{ variables.URL }}/api/1/rest/project/checkout/${{ variables.ORG_TEST }}/${{ variables.PROJECT_SPACE_TEST }}/$(Build.BuildNumber) \
      export RESULT=$(curl -X POST ${{ variables.URL }}/api/2/5b92a17b2cf68b1b9651a357/rest/project/checkout/${{ variables.ORG_TEST }}/${{ variables.PROJECT_SPACE_TEST }}/$(Build.BuildNumber) \
      -u $USER:$PASS \
      -H "Content-Type: application/json" \
      -d '{"repo":"'$REPO'","ref":"'$BRANCH'"}' \
      --trace-ascii /dev/stdout)
      echo "##vso[task.setvariable variable=RESULT]$RESULT"
    displayName: Clone to Test Project
    env:
      USER: $(user)
      PASS: $(pass)
      REPO: $(Build.Repository.Name)
      BRANCH: new-release/$(Build.SourceBranchName)    
